---
  - name: Update Windows
    hosts: rds_servers
    tasks:
      - name: Install all security updates with automatic reboots
        ansible.windows.win_updates:
          category_names:
            - SecurityUpdates
            - CriticalUpdates
            - UpdateRollups
          reboot: yes
