---
#SetGpeditLocal
  - hosts: rds_servers
    tasks:
      - name: 1C RemoteFX
        ansible.windows.win_regedit:
          path: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
          name: fEnableRemoteFXAdvancedRemoteApp
          data: 0
          type: dword
