---
  - name: Powershell Windows
    hosts: rds_servers
    tasks:
#      - name: Run an executable and send data to the stdin for the executable
#        win_command: powershell.exe -
#        args:
#          stdin: Get-Service "w*" | Sort-Object status -Descending > c:\temp\111.txt
#       - name: Run remote PowerShell Script
#         win_command: powershell.exe -ExecutionPolicy ByPass -File C:/temp/powershellscript.ps1
#       - name: Run remote PowerShell script
#         win_shell: c:\temp\powershellscript.ps1	
       - name: PowerShell Directory Test and File Create
         win_shell: |
           $value = Test-Path -Path C:\temp
           if ($value) {
               New-Item C:\temp\test.txt -ItemType File
           }
