---
#RestartServerEveryDay
  - hosts: rds_servers
    tasks:
      - community.windows.win_scheduled_task:
         name: RestartServerEveryDay
         description: Run cmd command
         actions:
         - path: shutdown.exe
           arguments: -r -f -t 0
         triggers:
         - type: daily
           start_boundary: '2017-10-09T01:00:00'
         username: SYSTEM
         run_level: highest
         state: present
         stop_if_going_on_batteries: yes
         
